apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "profile-chart.fullname" . }}
  labels:
  {{- include "profile-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
  {{- include "profile-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "profile-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: api
              containerPort: 80
              protocol: TCP
          env:
            - name: HOMEWORK_LOGGING_OUTPUT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "profile-chart.fullname" . }}
                  key: LOGGING_OUTPUT
            - name: HOMEWORK_LOGGING_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "profile-chart.fullname" . }}
                  key: LOGGING_FORMAT
            - name: HOMEWORK_LOGGING_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "profile-chart.fullname" . }}
                  key: LOGGING_LEVEL
            - name: HOMEWORK_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "profile-chart.fullname" . }}
                  key: DB_PORT
            - name: HOMEWORK_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "profile-chart.fullname" . }}
                  key: DB_HOST
            - name: HOMEWORK_DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "profile-chart.fullname" . }}
                  key: DB_DATABASE
            - name: HOMEWORK_DB_LOGIN
              valueFrom:
                secretKeyRef:
                  name: homework-secret
                  key: DB_LOGIN
            - name: HOMEWORK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homework-secret
                  key: DB_PASSWORD