apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "homework-chart.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /otusapp(/?)(.*)
            backend:
              serviceName: {{ include "homework-chart.fullname" . }}
              servicePort: {{ .Values.service.port }}